eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8765

spring:
  application:
    name: api-gateway

zuul:
  ignoredServices: "*"
  routes:
    service-hi:
      path: /hi/**
      serviceId: service-hi
